import { relations, sql } from 'drizzle-orm';
import {
  boolean,
  customType,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  vector,
} from 'drizzle-orm/pg-core';
import type { AdapterAccountType } from 'next-auth/adapters';

/* --------------------------------------------------------------- helpers */

/**
 * Postgres `tsvector`. Drizzle has no built-in for it; the column below is
 * generated by the database, so the app only ever reads it.
 */
const tsvector = customType<{ data: string; driverData: string }>({
  dataType() {
    return 'tsvector';
  },
});

/* ------------------------------------------------------------------ enums */

export const licenseTypeEnum = pgEnum('license_type', ['perpetual', 'subscription']);
export const billingIntervalEnum = pgEnum('billing_interval', ['none', 'monthly', 'annual']);
export const synonymKindEnum = pgEnum('synonym_kind', ['protocol', 'vendor', 'device', 'concept']);
export const userRoleEnum = pgEnum('user_role', ['buyer', 'sales', 'admin']);
export const quoteStatusEnum = pgEnum('quote_status', [
  'draft',
  'pending_approval',
  'sent',
  'viewed',
  'accepted',
  'converted',
  'expired',
  'rejected',
]);
export const quoteActorEnum = pgEnum('quote_actor', ['user', 'agent', 'system']);
export const subscriptionStatusEnum = pgEnum('subscription_status', [
  'trialing',
  'active',
  'past_due',
  'canceled',
  'unpaid',
  'incomplete',
]);
export const syncStateEnum = pgEnum('sync_state', ['pending', 'synced', 'failed', 'drifted']);
export const orderStatusEnum = pgEnum('order_status', [
  'pending_payment',
  'paid',
  'po_received',
  'fulfilled',
  'cancelled',
]);
export const paymentMethodEnum = pgEnum('payment_method', ['card', 'purchase_order']);
export const webhookStatusEnum = pgEnum('webhook_status', [
  'received',
  'processed',
  'failed',
  'dead_lettered',
]);

/* --------------------------------------------------------------- catalog */

export const products = pgTable(
  'products',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    sku: text('sku').notNull().unique(),
    name: text('name').notNull(),
    slug: text('slug').notNull().unique(),
    category: text('category').notNull(),
    description: text('description').notNull(),
    protocols: text('protocols').array().notNull().default(sql`ARRAY[]::text[]`),
    vendorCompat: text('vendor_compat').array().notNull().default(sql`ARRAY[]::text[]`),
    licenseType: licenseTypeEnum('license_type').notNull(),
    specs: jsonb('specs').notNull().default(sql`'{}'::jsonb`),
    active: boolean('active').notNull().default(true),
    /**
     * Weighted lexeme vector maintained by Postgres. Name and SKU carry weight
     * A so an exact part number outranks a description that merely mentions it;
     * protocols and vendor names carry B; prose carries C. Built by
     * `tagbridge_product_search_text`, declared in migration 0000 and widened
     * in 0003 — an index expression has to be IMMUTABLE, and
     * `array_to_string` is not.
     *
     * Spec values are indexed at weight B alongside protocols and vendors:
     * that is where compatibility facts live ("SAML, OIDC", "hot standby"),
     * and indexing only the keys made them unfindable.
     */
    searchVector: tsvector('search_vector').generatedAlwaysAs(
      sql`tagbridge_product_search_text(name, sku, description, protocols, vendor_compat, specs)`,
    ),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('products_category_idx').on(t.category),
    index('products_active_idx').on(t.active),
    index('products_fts_idx').using('gin', t.searchVector),
  ],
);

export const productVariants = pgTable(
  'product_variants',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    productId: uuid('product_id')
      .notNull()
      .references(() => products.id, { onDelete: 'cascade' }),
    sku: text('sku').notNull().unique(),
    tagCapacity: integer('tag_capacity'),
    tier: text('tier').notNull(),
    listPriceCents: integer('list_price_cents').notNull(),
    billingInterval: billingIntervalEnum('billing_interval').notNull().default('none'),
    active: boolean('active').notNull().default(true),
  },
  (t) => [index('product_variants_product_idx').on(t.productId)],
);

export const priceTiers = pgTable(
  'price_tiers',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    variantId: uuid('variant_id')
      .notNull()
      .references(() => productVariants.id, { onDelete: 'cascade' }),
    minQty: integer('min_qty').notNull(),
    unitPriceCents: integer('unit_price_cents').notNull(),
  },
  (t) => [uniqueIndex('price_tiers_variant_min_qty_uq').on(t.variantId, t.minQty)],
);

export const productEmbeddings = pgTable(
  'product_embeddings',
  {
    productId: uuid('product_id')
      .primaryKey()
      .references(() => products.id, { onDelete: 'cascade' }),
    embedding: vector('embedding', { dimensions: 1536 }).notNull(),
    sourceText: text('source_text').notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('product_embeddings_hnsw_idx').using(
      'hnsw',
      t.embedding.op('vector_cosine_ops'),
    ),
  ],
);

export const synonyms = pgTable(
  'synonyms',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    term: text('term').notNull(),
    canonical: text('canonical').notNull(),
    kind: synonymKindEnum('kind').notNull(),
  },
  (t) => [
    uniqueIndex('synonyms_term_canonical_uq').on(t.term, t.canonical),
    index('synonyms_term_idx').on(t.term),
    index('synonyms_canonical_idx').on(t.canonical),
  ],
);

/* ------------------------------------------------------------------ auth */

export const users = pgTable('users', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name'),
  email: text('email').notNull().unique(),
  emailVerified: timestamp('email_verified', { withTimezone: true }),
  image: text('image'),
  role: userRoleEnum('role').notNull().default('buyer'),
  companyName: text('company_name'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const accounts = pgTable(
  'accounts',
  {
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    type: text('type').$type<AdapterAccountType>().notNull(),
    provider: text('provider').notNull(),
    providerAccountId: text('provider_account_id').notNull(),
    refresh_token: text('refresh_token'),
    access_token: text('access_token'),
    expires_at: integer('expires_at'),
    token_type: text('token_type'),
    scope: text('scope'),
    id_token: text('id_token'),
    session_state: text('session_state'),
  },
  (t) => [primaryKey({ columns: [t.provider, t.providerAccountId] })],
);

export const sessions = pgTable('sessions', {
  sessionToken: text('session_token').primaryKey(),
  userId: uuid('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),
  expires: timestamp('expires', { withTimezone: true }).notNull(),
});

export const verificationTokens = pgTable(
  'verification_tokens',
  {
    identifier: text('identifier').notNull(),
    token: text('token').notNull(),
    expires: timestamp('expires', { withTimezone: true }).notNull(),
  },
  (t) => [primaryKey({ columns: [t.identifier, t.token] })],
);

/* ------------------------------------------------------------------ cart */

export const carts = pgTable(
  'carts',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id').references(() => users.id, { onDelete: 'cascade' }),
    anonymousId: text('anonymous_id'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('carts_user_idx').on(t.userId), index('carts_anon_idx').on(t.anonymousId)],
);

export const cartItems = pgTable(
  'cart_items',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    cartId: uuid('cart_id')
      .notNull()
      .references(() => carts.id, { onDelete: 'cascade' }),
    variantId: uuid('variant_id')
      .notNull()
      .references(() => productVariants.id, { onDelete: 'restrict' }),
    qty: integer('qty').notNull(),
  },
  (t) => [uniqueIndex('cart_items_cart_variant_uq').on(t.cartId, t.variantId)],
);

/* ---------------------------------------------------------------- quotes */

export const quotes = pgTable(
  'quotes',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    number: text('number').notNull().unique(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    status: quoteStatusEnum('status').notNull().default('draft'),
    subtotalCents: integer('subtotal_cents').notNull().default(0),
    expiresAt: timestamp('expires_at', { withTimezone: true }),
    agentNotes: text('agent_notes'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('quotes_user_idx').on(t.userId), index('quotes_status_idx').on(t.status)],
);

export const quoteLineItems = pgTable(
  'quote_line_items',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    quoteId: uuid('quote_id')
      .notNull()
      .references(() => quotes.id, { onDelete: 'cascade' }),
    variantId: uuid('variant_id')
      .notNull()
      .references(() => productVariants.id, { onDelete: 'restrict' }),
    qty: integer('qty').notNull(),
    // Always computed server-side from price_tiers. Never accepted from a model.
    unitPriceCents: integer('unit_price_cents').notNull(),
  },
  (t) => [index('quote_line_items_quote_idx').on(t.quoteId)],
);

export const quoteEvents = pgTable(
  'quote_events',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    quoteId: uuid('quote_id')
      .notNull()
      .references(() => quotes.id, { onDelete: 'cascade' }),
    type: text('type').notNull(),
    actor: quoteActorEnum('actor').notNull(),
    payload: jsonb('payload').notNull().default(sql`'{}'::jsonb`),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('quote_events_quote_idx').on(t.quoteId)],
);

/* ---------------------------------------------------------------- orders */

export const orders = pgTable(
  'orders',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    number: text('number').notNull().unique(),
    userId: uuid('user_id').references(() => users.id, { onDelete: 'set null' }),
    email: text('email').notNull(),
    companyName: text('company_name'),
    status: orderStatusEnum('status').notNull(),
    paymentMethod: paymentMethodEnum('payment_method').notNull(),
    /** Server-computed from price_tiers at the moment the order was placed. */
    subtotalCents: integer('subtotal_cents').notNull(),
    currency: text('currency').notNull().default('usd'),
    stripeSessionId: text('stripe_session_id').unique(),
    poNumber: text('po_number'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('orders_user_idx').on(t.userId), index('orders_status_idx').on(t.status)],
);

export const orderItems = pgTable(
  'order_items',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    orderId: uuid('order_id')
      .notNull()
      .references(() => orders.id, { onDelete: 'cascade' }),
    variantId: uuid('variant_id')
      .notNull()
      .references(() => productVariants.id, { onDelete: 'restrict' }),
    qty: integer('qty').notNull(),
    unitPriceCents: integer('unit_price_cents').notNull(),
    lineTotalCents: integer('line_total_cents').notNull(),
    /** Frozen at order time: the catalog may change, the order may not. */
    productNameSnapshot: text('product_name_snapshot').notNull(),
    variantSkuSnapshot: text('variant_sku_snapshot').notNull(),
  },
  (t) => [index('order_items_order_idx').on(t.orderId)],
);

/* --------------------------------------------------------- subscriptions */

export const subscriptions = pgTable(
  'subscriptions',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    providerId: text('provider_id').notNull().unique(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    variantId: uuid('variant_id')
      .notNull()
      .references(() => productVariants.id, { onDelete: 'restrict' }),
    status: subscriptionStatusEnum('status').notNull(),
    currentPeriodEnd: timestamp('current_period_end', { withTimezone: true }),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('subscriptions_user_idx').on(t.userId)],
);

export const erpSyncRecords = pgTable(
  'erp_sync_records',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    subscriptionId: uuid('subscription_id')
      .notNull()
      .references(() => subscriptions.id, { onDelete: 'cascade' }),
    erpRef: text('erp_ref').notNull(),
    lastSyncedAt: timestamp('last_synced_at', { withTimezone: true }),
    state: syncStateEnum('state').notNull().default('pending'),
    driftDetected: boolean('drift_detected').notNull().default(false),
  },
  (t) => [uniqueIndex('erp_sync_records_subscription_uq').on(t.subscriptionId)],
);

export const webhookEvents = pgTable(
  'webhook_events',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    providerEventId: text('provider_event_id').notNull().unique(),
    type: text('type').notNull(),
    payload: jsonb('payload').notNull(),
    // Provider-assigned event time. Ordering is resolved on this, never arrival order.
    occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull(),
    receivedAt: timestamp('received_at', { withTimezone: true }).notNull().defaultNow(),
    processedAt: timestamp('processed_at', { withTimezone: true }),
    attempts: integer('attempts').notNull().default(0),
    status: webhookStatusEnum('status').notNull().default('received'),
    lastError: text('last_error'),
  },
  (t) => [index('webhook_events_status_idx').on(t.status)],
);

/* ------------------------------------------------------------- audit log */

export const auditLog = pgTable(
  'audit_log',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    actor: text('actor').notNull(),
    action: text('action').notNull(),
    resource: text('resource').notNull(),
    before: jsonb('before'),
    after: jsonb('after'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('audit_log_resource_idx').on(t.resource)],
);

/* ------------------------------------------------------------- relations */

export const productsRelations = relations(products, ({ many, one }) => ({
  variants: many(productVariants),
  embedding: one(productEmbeddings, {
    fields: [products.id],
    references: [productEmbeddings.productId],
  }),
}));

export const productVariantsRelations = relations(productVariants, ({ one, many }) => ({
  product: one(products, { fields: [productVariants.productId], references: [products.id] }),
  priceTiers: many(priceTiers),
}));

export const priceTiersRelations = relations(priceTiers, ({ one }) => ({
  variant: one(productVariants, {
    fields: [priceTiers.variantId],
    references: [productVariants.id],
  }),
}));

export const quotesRelations = relations(quotes, ({ one, many }) => ({
  user: one(users, { fields: [quotes.userId], references: [users.id] }),
  lineItems: many(quoteLineItems),
  events: many(quoteEvents),
}));

export const quoteLineItemsRelations = relations(quoteLineItems, ({ one }) => ({
  quote: one(quotes, { fields: [quoteLineItems.quoteId], references: [quotes.id] }),
  variant: one(productVariants, {
    fields: [quoteLineItems.variantId],
    references: [productVariants.id],
  }),
}));

export const ordersRelations = relations(orders, ({ one, many }) => ({
  user: one(users, { fields: [orders.userId], references: [users.id] }),
  items: many(orderItems),
}));

export const orderItemsRelations = relations(orderItems, ({ one }) => ({
  order: one(orders, { fields: [orderItems.orderId], references: [orders.id] }),
  variant: one(productVariants, {
    fields: [orderItems.variantId],
    references: [productVariants.id],
  }),
}));

export type Product = typeof products.$inferSelect;
export type Order = typeof orders.$inferSelect;
export type OrderStatus = (typeof orderStatusEnum.enumValues)[number];
export type PaymentMethod = (typeof paymentMethodEnum.enumValues)[number];
export type NewProduct = typeof products.$inferInsert;
export type ProductVariant = typeof productVariants.$inferSelect;
export type PriceTier = typeof priceTiers.$inferSelect;
export type User = typeof users.$inferSelect;
export type UserRole = (typeof userRoleEnum.enumValues)[number];
export type QuoteStatus = (typeof quoteStatusEnum.enumValues)[number];
