/**
 * Records a real MCP session against the stdio server and writes it to
 * docs/mcp-session.md.
 *
 * Generated rather than hand-written, so the transcript in the README is
 * evidence rather than an illustration: re-run it and it either reproduces or
 * the docs are wrong. Every response below is what the server actually sent.
 */
import { spawn } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { createInterface } from 'node:readline';
import path from 'node:path';

interface Exchange {
  note: string;
  request: unknown;
  response: unknown;
}

async function main(): Promise<void> {
  const child = spawn('npx', ['tsx', 'scripts/mcp-stdio.ts'], {
    cwd: process.cwd(),
    env: { ...process.env, TAGBRIDGE_MCP_USER: 'buyer@example.com' },
    stdio: ['pipe', 'pipe', 'inherit'],
  });

  const lines = createInterface({ input: child.stdout });
  const pending: ((value: unknown) => void)[] = [];
  lines.on('line', (line) => {
    const trimmed = line.trim();
    if (trimmed.length === 0) return;
    pending.shift()?.(JSON.parse(trimmed));
  });

  const send = (message: unknown): Promise<unknown> =>
    new Promise((resolve) => {
      pending.push(resolve);
      child.stdin.write(`${JSON.stringify(message)}\n`);
    });

  const exchanges: Exchange[] = [];
  const step = async (note: string, request: unknown): Promise<unknown> => {
    const response = await send(request);
    exchanges.push({ note, request, response });
    return response;
  };

  await step('The client opens the connection.', {
    jsonrpc: '2.0',
    id: 1,
    method: 'initialize',
    params: {
      protocolVersion: '2025-06-18',
      capabilities: {},
      clientInfo: { name: 'claude-desktop', version: '1.0.0' },
    },
  });

  await step('It asks what this server can do.', {
    jsonrpc: '2.0',
    id: 2,
    method: 'tools/list',
  });

  const compat = (await step(
    'The buyer describes what they have and what they want it to reach.',
    {
      jsonrpc: '2.0',
      id: 3,
      method: 'tools/call',
      params: {
        name: 'resolveCompatibility',
        arguments: {
          sourceDevice: 'allen-bradley',
          destinationSystem: 'sql-server',
          tagCount: 5000,
          transport: 'ethernet-ip',
        },
      },
    },
  )) as { result: { content: { text: string }[] } };

  const bundle = JSON.parse(compat.result.content[0]!.text) as {
    bundle: { sku: string }[];
  };
  const sku = bundle.bundle[0]!.sku;

  const search = (await step('It turns the resolver’s SKU into something quotable.', {
    jsonrpc: '2.0',
    id: 4,
    method: 'tools/call',
    params: { name: 'searchProducts', arguments: { query: sku, limit: 1 } },
  })) as { result: { content: { text: string }[] } };

  const hits = JSON.parse(search.result.content[0]!.text) as {
    hits: { variantId: string }[];
  };
  const variantId = hits.hits[0]!.variantId;

  await step('It checks the price. This is the only place a number comes from.', {
    jsonrpc: '2.0',
    id: 5,
    method: 'tools/call',
    params: { name: 'getPricing', arguments: { variantId, qty: 4 } },
  });

  await step(
    'It tries to set the price itself. The guardrail refuses, and says why.',
    {
      jsonrpc: '2.0',
      id: 6,
      method: 'tools/call',
      params: {
        name: 'createQuote',
        arguments: { lines: [{ variantId, qty: 4, unitPriceCents: 100 }] },
      },
    },
  );

  await step('It drafts the quote properly, sending only ids and quantities.', {
    jsonrpc: '2.0',
    id: 7,
    method: 'tools/call',
    params: {
      name: 'createQuote',
      arguments: {
        lines: [{ variantId, qty: 4 }],
        notes: 'Allen-Bradley to SQL Server, 5,000 tags.',
      },
    },
  });

  await step('It tries to approve its own quote. It cannot.', {
    jsonrpc: '2.0',
    id: 8,
    method: 'tools/call',
    params: { name: 'sendQuoteEmail', arguments: { quoteId: crypto.randomUUID() } },
  });

  child.stdin.end();
  child.kill();

  const body = [
    '# A real MCP session',
    '',
    'Generated by `pnpm mcp:transcript`, which drives the stdio server in',
    '`scripts/mcp-stdio.ts` and records what it actually returns. Nothing here',
    'is written by hand — re-run it and it reproduces, or the docs are wrong.',
    '',
    'The client acts as `buyer@example.com`. Two of the eight exchanges are',
    'refusals, and they are the interesting ones: the price a client tried to',
    'set, and the approval it tried to grant itself.',
    '',
    ...exchanges.flatMap((exchange, index) => [
      `## ${index + 1}. ${exchange.note}`,
      '',
      '```json',
      JSON.stringify(exchange.request, null, 2),
      '```',
      '',
      '```json',
      JSON.stringify(exchange.response, null, 2),
      '```',
      '',
    ]),
  ].join('\n');

  const target = path.join(process.cwd(), 'docs', 'mcp-session.md');
  mkdirSync(path.dirname(target), { recursive: true });
  writeFileSync(target, body);
  console.log(`wrote ${target} (${exchanges.length} exchanges)`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
